version: 0.0
os: linux
files:
  - source: ./target/weatherSearch-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/weather
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

