version: 0.2

phases:
  pre_build:
    commands:
      - mvn --version
  build:
    commands:
      - echo Build of SampleAPIApp started on `date`
      - mvn clean package -P prod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/weatherSearch-0.0.1.jar
    - appspec.yml
    - 'scripts/**/*'
